### ISSUE TITLE
Block caret updates in latest dev

### ISSUE THREAD

**Issue by maxim** [jhermsmeier/chelevra.tmtheme#1]
Hey Jonas,

ST3 just updated their caret rendering in [build 3190](https://www.sublimetext.com/3dev), and it made caret look super light for this theme.

<img width="86" alt="screen shot 2019-02-19 at 11 10 17" src="https://user-images.githubusercontent.com/7758/53029616-4828f480-3437-11e9-9241-ee9a04dccf22.png">

This is with using NeoVintageous plugin that makes cursor into a block in standard mode. (If you can't see it, that's the issue 😃)

I think the theme uses selection color by default, but block caret now can have its own dedicated color from what I understood reading [this thread](https://forum.sublimetext.com/t/caret-gate-unwanted-changes-to-caret-rendering/41925).

Would be superb if you could tweak the theme. I found the theme through Colorsublime, so an update there would be ideal.

P.S. This has been my absolute favorite theme for years. ❤️ I love it so much that even if other editors become as fast as ST3, I probably wouldn't wanna switch until Ayu + this theme are there.

P.P.S. Very happy to learn about the Material variant. The more variations on this theme, the better.

**Comment by jhermsmeier** [comment]
Hey Max, thanks for bringing this to my attention! I would've missed it, as I've been running the stable builds lately, and don't use a block cursor :D

The fix should be easy from what I read - I'll see to it shortly and also update it on Colorsublime (that might take a little longer for the PR to go through).

I'm immensely happy to hear you're liking it so much :) I have been thinking about making it available for other editors as well, but since I only use Sublime I've never remembered to do so.

**Comment by jhermsmeier** [comment]
Alright; I fixed the `block_caret` being invisible (https://github.com/jhermsmeier/chelevra.tmtheme/commit/8e67cbcb4319ef03ee70448ed83e6afa7e33a9a7), and filed a PR (https://github.com/Colorsublime/Colorsublime-Themes/pull/390) to update them in Colorsublime.

Closing this then, thanks again! :)

**Comment by maxim** [comment]
@jhermsmeier Wow, that's impressively quick, thank you! I'm gonna pull your version from here for now. Seriously, it's such a perfect combination of _just enough_ color. Every other theme is either too much or completely grayscale. And that exact shade of green looks perfect on the dark background, which comes through even in my tiny screenshot above. Tastes may differ, but this is what I call tasteful.

**Comment by jhermsmeier** [comment]
Thank you for the kind words, I'm humbled! :)

> Seriously, it's such a perfect combination of _just enough_ color. Every other theme is either too much or completely grayscale.

That sums up the reason this exists perfectly. The _"just enough color"_ is such a good way of describing it (I might steal that as a tag line, if I may) – the important thing for me is that I can visually tokenize quickly into a kind of [action name value] set, because I feel that makes reading and understanding code faster – too much color makes that difficult, and it's also hard to keep a good, level contrast with too many colors.

**Comment by maxim** [comment]
Good point about visual tokenization. I think you nailed the reason why the theme agrees with my brain so well. Of course, feel free to use any of this as a tagline. :)

Since we're on the subject, I decided to try and tweak the block to be a little less bright. I figured, it doesn't need as much brightness as a line cursor. Tried going with `6080A0`.

Before
<img width="98" alt="screen shot 2019-02-21 at 15 11 35" src="https://user-images.githubusercontent.com/7758/53198699-0c369080-35eb-11e9-9bae-4e6c725010b8.png">

After
<img width="100" alt="screen shot 2019-02-21 at 15 00 13" src="https://user-images.githubusercontent.com/7758/53198350-389ddd00-35ea-11e9-8c97-caf152d59f71.png">

I think this is closer to the color I'd want on a block, but still not 100% there. Definitely not proposing a change, this is your theme, but just sharing something I tried.

**Comment by jhermsmeier** [comment]
Yeah, I thought this will need some tweaking – I'll fiddle around with it some more.

> Definitely not proposing a change, this is your theme, but just sharing something I tried.

Oh, please do let me know if there's something that might need improvement, or other suggestions! Even if I'm not going to incorporate something, asking can't hurt ;)

**Comment by jhermsmeier** [comment]
So, I've been testing some colors and opacities, but nothing really sits well – I think this is due to the current character the caret is on not being inverted in color, making it hard to see with anything but the darkest shades.

**Comment by maxim** [comment]
Yeah, it's an annoying limitation. 😞  I've just been rolling with my `6080A0` from above comment for now. So far every other color came through the block pretty well.
