### ISSUE TITLE
The latest ayu theme has darker background

### ISSUE THREAD

**Issue by maxim** [jhermsmeier/chelevra.tmtheme#3]
The newly updated background of Ayu Dark is `0A0E14`, so you may notice that this scheme's bg color no longer matches it. I changed it [here](https://github.com/jhermsmeier/chelevra.tmtheme/blob/master/chelevra-ayu.tmTheme#L15) locally and the result looks good, albeit green keywords gained a bit of extra contrast against background.

<img width="154" alt="Screen Shot 2019-03-26 at 08 23 25" src="https://user-images.githubusercontent.com/7758/54996742-7b175880-4fa0-11e9-9f7e-77fb82cee718.png">

**Comment by jhermsmeier** [comment]
Yup, I noticed that yesterday as well – fixed now. I still have a few minor things I'd like to change, and then I'll PR another update to Colorsublime
